blank_issues_enabled: false
contact_links:
  - name: BitAI related issues
    url: https://github.com/stackblitz/bitai.agent/issues/new/choose
    about: Report issues related to BitAI agent
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other BitAI agent users.
